export const SKILL_OPTIONS = [
  { value: 'JavaScript', icon: '⚡', category: 'Technical' },
  { value: 'Python', icon: '🐍', category: 'Technical' },
  { value: 'Data Analysis', icon: '📊', category: 'Technical' },
  { value: 'UX/UI', icon: '🎨', category: 'Design' },
  { value: 'AI/ML', icon: '🤖', category: 'Technical' },
  { value: 'Leadership', icon: '👥', category: 'Soft Skills' },
  { value: 'Public Speaking', icon: '🎤', category: 'Soft Skills' },
  { value: 'Project Management', icon: '📋', category: 'Soft Skills' },
]

export const LEAD_ROLE = [
  { label: "Presidente", value: "president" },
  { label: "Vicepresidente", value: "vicepresident" },
  { label: "Tesorero", value: "treasurer" },
  { label: "Director de Liderazgo", value: "leadership_director" },
  { label: "Director de Excelencia Académica", value: "academic_excellence_director" },
  { label: "Director de Impulso Femenino", value: "female_empowerment_director" },
  { label: "Directora de Desarrollo Profesional", value: "professional_development_director" },
  { label: "Director de Impacto Comunitario", value: "community_impact_director" },
  { label: "Director de Desarrollo del Capítulo", value: "chapter_development_director" },
  { label: "Director de LEAD Academia", value: "lead_academy_director" },
  { label: "Participante", value: "participant" },
  { label: "Otro", value: "other" },
];

export const LEAD_CHAPTER_OPTIONS = [
  { label: "LEAD PUCP", value: "leadpucp" },
  { label: "LEAD UNMSM", value: "leadunmsm" },
  { label: "LEAD UTEC", value: "leadutec" },
  { label: "LEAD PACÍFICO", value: "leadpacifico" },
  { label: "LEAD VILLAREAL", value: "leadvillareal" },
  { label: "LEAD UNI", value: "leaduni" },
  { label: "LEAD UPC", value: "leadupc" },
  { label: "LEAD UPN", value: "leadupn" },
  { label: "LEAD TECSUP", value: "leadtecsup" },
  { label: "LEAD UTP", value: "leadutp" },
];


export const AVAILABILITY_OPTIONS = [
  { label: "No disponible", value: "not_available" },
  { label: "Tiempo completo", value: "full_time" },
  { label: "Medio tiempo", value: "part_time" },
  { label: "Pasantía", value: "internship" },
];

export const CAREER_OPTIONS = [
  "Biología",
  "Biotecnología",
  "Bioquímica",
  "Ciencias Ambientales",
  "Ciencias de la Computación",
  "Ciencias Físicas",
  "Ciencias Matemáticas",
  "Estadística",
  "Genética",
  "Microbiología",
  "Química",
  "Geología",
  "Geofísica",
  "Ingeniería de Sistemas",
  "Ingeniería de Software",
  "Ingeniería Informática",
  "Ciencia de Datos",
  "Ciberseguridad",
  "Inteligencia Artificial",
  "Ingeniería Civil",
  "Ingeniería Industrial",
  "Ingeniería Mecánica",
  "Ingeniería Electrónica",
  "Ingeniería Eléctrica",
  "Ingeniería Química",
  "Ingeniería de Telecomunicaciones",
  "Ingeniería de Minas",
  "Ingeniería Ambiental",
  "Ingeniería Biomédica",
  "Matemáticas",
  "Física",
  "Bioinformática",
  "Nanotecnología",
  "Arquitectura",
  "Tecnología Médica",
  "Otro",
];
